"""Export Wrenfield House for the walkthrough app, as a hybrid.

The app builds the house's structure itself — walls and what is in them,
floors, ceilings, roofs, stairs, stairwells, the site — from a scene spec,
so its editor can slide doors and windows along their walls and cut floors
for stairs. Blender contributes what is worth modelling: the furniture, the
fitted kitchen and bathrooms, the pictures on the walls. This script

  - builds the furnishings alone, from furnish.py, exactly as build_house.py
    places them in the full Blender house;
  - bakes their tiling textures and strips the cosmetic bevel modifiers,
    whose 2 mm rounds multiply the triangle count for no visible gain;
  - exports public/models/wrenfield_furnishings.glb, every top-level node of
    which becomes a movable piece in the app, named as it always was;
  - writes scripts/wrenfield-spec.json: the structure from structure.py and
    plan.py, the same data shell.py builds the Blender house from.

Coordinate note: Blender is Z-up, glTF is Y-up, so a plan point (x, y)
lands at (x, -y) on the app's XZ ground plane. Elevations carry over.

    blender --background --python export_app.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import bpy

from lib import furnish, geometry as g, materials as m, plan as P
from lib import structure as S


def clean():
    for coll in (bpy.data.objects, bpy.data.meshes, bpy.data.materials,
                 bpy.data.lights, bpy.data.cameras, bpy.data.collections):
        for item in list(coll):
            coll.remove(item, do_unlink=True)


def bake_tiling_textures():
    """Replace each node-driven Base Color with a real tiling image.

    glTF carries a constant colour or an image and nothing else, so the
    patterns are regenerated by lib/bake.py and plugged in as image textures.
    The geometry then gets world-space box UVs scaled to each material's tile
    size, which is what makes one 512px image cover a whole floor without
    unwrapping a single object.
    """
    import json as _json
    from lib import bake

    baked = 0
    for mat in bpy.data.materials:
        gen = mat.get("bake_gen")
        if not gen or not mat.use_nodes:
            continue
        bsdf = next((n for n in mat.node_tree.nodes if n.type == "BSDF_PRINCIPLED"), None)
        if not bsdf:
            continue

        rgb = bake.generate(gen, _json.loads(mat["bake_params"]), mat.name)
        if rgb is None:
            continue

        # Match the pattern's average to the flat colour that was already
        # tuned and measured in-app. Baking adds grout lines and board joints,
        # which drag the mean down and would otherwise darken every floor by
        # about a quarter; scaling per channel keeps the hue and restores the
        # tone, so the texture adds detail without re-opening the palette.
        flat = mat.get("flat_color")
        if flat is not None:
            import numpy as _np
            current = rgb.reshape(-1, 3).mean(axis=0)
            rgb = _np.clip(rgb * (_np.asarray(flat) / _np.maximum(current, 1e-4)), 0.0, 1.0)
        img = bake.to_blender_image(f"tex_{mat.name}", rgb)

        nt = mat.node_tree
        tex = nt.nodes.new("ShaderNodeTexImage")
        tex.image = img
        tex.interpolation = "Smart"
        tex.extension = "REPEAT"
        tex.location = (-400, 200)
        # The UVs are already built at the right scale, so the node reads them
        # straight through with no mapping in between.
        uv = nt.nodes.new("ShaderNodeUVMap")
        uv.uv_map = UV_NAME
        uv.location = (-620, 200)
        nt.links.new(uv.outputs["UV"], tex.inputs["Vector"])

        base = bsdf.inputs["Base Color"]
        for link in list(base.links):
            nt.links.remove(link)
        nt.links.new(tex.outputs["Color"], base)
        baked += 1

    print(f"TEXTURES_BAKED {baked}")
    build_box_uvs()


UV_NAME = "UVMap"


def build_box_uvs():
    """Box-project every mesh, per face, at its own material's tile size.

    A face is projected onto whichever world plane it most faces, so a floor
    takes its UVs from X/Y and a wall from X/Z or Y/Z. Scaling by the material
    means a 2.4 m plank tile and a 1.2 m carpet tile both come out at real
    size on the same object.
    """
    import bmesh

    done = 0
    for obj in bpy.data.objects:
        if obj.type != "MESH" or not obj.data.polygons:
            continue

        tiles = []
        for slot in obj.data.materials:
            tiles.append(float(slot["bake_tile"]) if slot and slot.get("bake_tile") else 0.0)
        if not any(tiles):
            continue

        mw = obj.matrix_world
        bm = bmesh.new()
        bm.from_mesh(obj.data)
        layer = bm.loops.layers.uv.get(UV_NAME) or bm.loops.layers.uv.new(UV_NAME)

        for face in bm.faces:
            tile = tiles[face.material_index] if face.material_index < len(tiles) else 0.0
            if tile <= 0:
                tile = 2.4
            n = (mw.to_3x3() @ face.normal)
            ax, ay, az = abs(n.x), abs(n.y), abs(n.z)
            for loop in face.loops:
                co = mw @ loop.vert.co
                if az >= ax and az >= ay:
                    u, v = co.x, co.y          # floors and ceilings
                elif ax >= ay:
                    u, v = co.y, co.z          # walls facing along X
                else:
                    u, v = co.x, co.z          # walls facing along Y
                loop[layer].uv = (u / tile, v / tile)

        bm.to_mesh(obj.data)
        bm.free()
        done += 1

    print(f"UV_PROJECTED {done}")


def flatten_procedural_materials():
    """Give every node-driven material a constant Base Color for export.

    The glTF exporter can write a baseColorFactor or a baseColorTexture and
    nothing else. A Base Color fed by a Noise/Brick/ColorRamp graph matches
    neither, so it silently exports as white — which is how a fully painted
    house arrived in the app as a colourless one. Each material recorded the
    colour its graph averages to when it was built; swap that in.
    """
    flattened = 0
    for mat in bpy.data.materials:
        if not mat.use_nodes:
            continue
        bsdf = next((n for n in mat.node_tree.nodes
                     if n.type == "BSDF_PRINCIPLED"), None)
        if not bsdf:
            continue
        base = bsdf.inputs["Base Color"]
        if not base.is_linked:
            continue
        flat = mat.get("flat_color")
        if flat is None:
            continue
        for link in list(base.links):
            mat.node_tree.links.remove(link)
        base.default_value = (flat[0], flat[1], flat[2], 1.0)
        flattened += 1
    print(f"MATERIALS_FLATTENED {flattened}")


def strip_bevels():
    n = 0
    for o in bpy.data.objects:
        for mod in list(o.modifiers):
            if mod.type == "BEVEL":
                o.modifiers.remove(mod)
                n += 1
    print(f"BEVELS_STRIPPED {n}")


def visible_meshes():
    return [o for o in bpy.data.objects
            if o.type == "MESH" and not o.hide_render and not o.hide_viewport]


def evaluated_tris():
    """Triangle counts as the exporter will see them, modifiers applied."""
    dg = bpy.context.evaluated_depsgraph_get()
    per_mesh = {}   # mesh datablock -> (tris, [objects])
    for o in visible_meshes():
        me = bpy.data.meshes.new_from_object(o.evaluated_get(dg))
        tris = sum(len(p.vertices) - 2 for p in me.polygons)
        bpy.data.meshes.remove(me)
        key = o.data
        t, objs = per_mesh.get(key, (0, []))
        per_mesh[key] = (tris, objs + [o])
    return per_mesh


def triangle_count():
    """Triangles as the exporter will see them, modifiers applied."""
    bpy.context.view_layer.update()
    total = sum(t * len(o) for t, o in evaluated_tris().values())
    print(f"TRIS {total}")
    return total


LEAF_TRIMS = {"door_leaf": "trim_white", "cab_navy": "trim_charcoal",
              "cab_sage": "trim_white", "cab_oak": "trim_oak"}
HANDLE_TRIMS = {"brass": "metal_brass", "chrome": "metal_chrome",
                "black_metal": "metal_black", "steel": "metal_chrome"}

FLOOR_MAP = {"oak": "oak_parquet", "walnut": "walnut_boards",
             "tile_stone": "slate_tile", "tile_white": "ceramic_tile_white",
             "tile_slate": "slate_tile", "carpet_grey": "carpet_grey",
             "carpet_beige": "carpet_beige", "concrete": "polished_concrete"}

WALL_MAP = {"wall_white": "paint_white", "wall_warm": "paint_warm_white",
            "wall_sage": "paint_sage", "wall_clay": "paint_clay",
            "wall_charcoal": "paint_charcoal"}

GROUND_MAP = {"grass": "lawn", "tarmac": "tarmac_surface", "paving": "paving_slab"}

ROOM_NAMES = {"wc": "Cloakroom", "bed1": "Principal Bedroom", "loftbath": "Loft Shower Room",
              "ensuite1": "En-suite 1", "ensuite2": "En-suite 2", "bed2": "Bedroom 2",
              "bed3": "Bedroom 3", "bed4": "Bedroom 4", "bath": "Family Bathroom"}

LEVEL_KEY = {"ground": "g", "first": "f", "attic": "a"}


def xz(point):
    """A plan point on the app's ground plane."""
    return [round(point[0], 4), round(-point[1], 4)]


def app_opening(o, wall_id, index):
    entry = {
        "id": f"{wall_id}-{index}",
        "offset": round(o.offset, 4),
        "width": round(o.width, 4),
        "height": round(o.height, 4),
        "sill": round(o.sill, 4),
    }
    if o.kind == "door":
        entry["type"] = "door"
        entry["door"] = {
            "type": "hinged",
            "swing": "inward_left" if o.opts.get("swing", 0) < 0 else "inward_right",
            "leaf": LEAF_TRIMS.get(o.opts.get("leaf", "door_leaf"), "trim_white"),
            "frame": "trim_white",
            "handle": HANDLE_TRIMS.get(o.opts.get("handle", "brass"), "metal_brass"),
        }
    elif o.kind == "doorway":
        entry["type"] = "doorway"
    else:
        # Windows and French windows, which are windows down to the floor.
        entry["type"] = "window"
        entry["frame"] = "trim_white"
        entry["panes"] = [o.opts.get("panes_x", 2), o.opts.get("panes_z", 2)]
        entry["cill"] = o.sill > 0.2
    return entry


def app_wall(wall_id, spec, group, external, trims):
    """One wall of structure.py in the app's terms.

    The app's side A is a wall's right-hand face, going from start to end —
    its +Z once flipped onto the XZ plane — which is Blender's side B, and
    the other way round. External rings run anticlockwise, so their left,
    the app's side B, is indoors.
    """
    start, end, openings = spec[0], spec[1], spec[2]
    if external:
        # Smooth render outside — the app's plaster texture is a rough
        # mottle, far from Blender's render — and painted walls within.
        finish, back = "paint_warm_white", "paint_white"
    else:
        left = spec[3] if len(spec) > 3 else "wall_white"
        right = spec[4] if len(spec) > 4 else left
        finish, back = WALL_MAP[right], WALL_MAP[left]
    wall = {
        "id": wall_id,
        "start": xz(start),
        "end": xz(end),
        "height": round(group["height"], 4),
        "thickness": P.EXT if external else P.INT,
        "finish": finish,
        "finish_back": back,
        "reveal": "trim_white",
        "base_height": round(group["base"], 4),
        "openings": [app_opening(o, wall_id, j)
                     for j, o in enumerate(sorted(openings, key=lambda o: o.offset))],
    }
    if trims:
        wall["trims"] = trims
    return wall


def rail_sides(points, void):
    """Which sides of a stairwell a landing rail runs along, in the app's
    frame for the opening: x-/x+ across it, z-/z+ along it, +z being south."""
    xs = [p[0] for p in void]
    ys = [p[1] for p in void]
    cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    sides = []
    for a, b in zip(points, points[1:]):
        if abs(a[0] - b[0]) < 1e-3:
            sides.append("x+" if a[0] > cx else "x-")
        else:
            sides.append("z+" if a[1] < cy else "z-")
    return sides


def app_spec():
    """The structure, as the app's scene spec: rooms, walls, roofs, stairs
    and stairwells. Furniture, spawns and the car are the seed's."""
    rooms = []
    storeys = [("ground", P.GROUND_ROOMS, P.G, P.H_G),
               ("first", P.FIRST_ROOMS, P.F1, P.H_F1),
               ("attic", P.ATTIC_ROOMS, P.F2, P.H_F2)]
    for label, table, elevation, height in storeys:
        for rid, (poly, floor, _wall) in table.items():
            rooms.append({
                "id": f"{label}-{rid}",
                "name": ROOM_NAMES.get(rid, rid.replace("_", " ").title()),
                "polygon": [xz(p) for p in poly],
                "voids": [],
                "floor_finish": FLOOR_MAP.get(floor, "oak_parquet"),
                "ceiling_finish": "ceiling_white",
                "height": height,
                "elevation": elevation,
            })
    rooms.append({
        "id": "ground-garage", "name": "Garage",
        "polygon": [xz(p) for p in S.GARAGE["floor"]], "voids": [],
        "floor_finish": "polished_concrete", "ceiling_finish": "ceiling_white",
        "height": S.GARAGE["height"], "elevation": S.GARAGE["base"],
    })
    for name, label, rect, finish in S.SITE_TILES:
        rooms.append({
            "id": f"site-{name}", "name": label,
            "polygon": [xz(p) for p in rect], "voids": [],
            "floor_finish": GROUND_MAP[finish], "ceiling_finish": "none",
            "height": 0.05, "elevation": 0,
        })

    walls = []
    for group in S.RINGS:
        key = LEVEL_KEY[group["level"]]
        # Skirting and casings indoors — though not round the eaves, which
        # face the roof void behind the loft's knee walls.
        trims = None if group["level"] == "attic" else "b"
        for i, spec in enumerate(group["walls"]):
            walls.append(app_wall(f"{key}-ext-{i}", spec, group, True, trims))
    for group in S.PARTITIONS:
        key = LEVEL_KEY[group["level"]]
        for i, spec in enumerate(group["walls"]):
            walls.append(app_wall(f"{key}-wall-{i}", spec, group, False, "both"))
    for i, spec in enumerate(S.GARAGE["walls"]):
        walls.append(app_wall(f"garage-ext-{i}", spec, S.GARAGE, True, None))

    roofs = []
    for r in S.ROOFS:
        roofs.append({
            "id": f"roof-{r['id']}",
            "type": "gable",
            "footprint": [xz(p) for p in P.rect(r["x0"], r["y0"], r["x1"], r["y1"])],
            "base_height": r["eaves"],
            "ridge_height": r["ridge"],
            # Blender's Y is the app's Z.
            "ridge_axis": "x" if r["ridge_axis"] == "x" else "z",
            "finish": "roof_terracotta",
            "gable_finish": "paint_warm_white",
            "overhang": r["overhang"],
            "thickness": r["thickness"],
            "soffit": "trim_white",
        })

    stairs, holes = [], []
    for f in S.FLIGHTS:
        # Every flight climbs Blender +Y, the app's -Z: a heading of 180.
        # Climbing that way, east is on the right.
        stairs.append({
            "id": f["id"],
            "start": [round((f["x0"] + f["x1"]) / 2, 4), round(-f["y0"], 4)],
            "direction": "south",
            "yaw": 180,
            "width": round(f["x1"] - f["x0"], 4),
            "base_height": f["base"],
            "top_height": f["top"],
            "run": round(f["y1"] - f["y0"], 4),
            "steps": f["steps"],
            "finish": "oak_parquet",
            "riser": "trim_white",
            "balustrade": {"east": "right", "west": "left", "both": "both"}[f["balustrade"]],
        })
        xs = [p[0] for p in f["void"]]
        ys = [p[1] for p in f["void"]]
        rail = next(r for r in S.LANDING_RAILS if r["flight"] == f["id"])
        holes.append({
            "id": f"hole-{f['id']}",
            "position": xz(((min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2)),
            "elevation": f["top"],
            "width": round(max(xs) - min(xs), 4),
            "depth": round(max(ys) - min(ys), 4),
            "yaw": 0,
            "stair_id": f["id"],
            "rails": rail_sides(rail["points"], f["void"]),
        })

    return {"rooms": rooms, "walls": walls, "roofs": roofs, "stairs": stairs,
            "floor_openings": holes}


def main():
    clean()
    mats = m.library()
    # The furnishings alone: the structure is the app's to build.
    cols = {k: g.collection(k) for k in ("ground", "first", "attic")}
    furnish.build(cols, mats)

    bake_tiling_textures()
    strip_bevels()
    total = triangle_count()

    out_glb = os.path.join(REPO, "public", "models", "wrenfield_furnishings.glb")
    bpy.ops.export_scene.gltf(
        filepath=out_glb,
        export_format="GLB",
        use_visible=True,
        export_apply=True,
        export_cameras=False,
        export_extras=False,
        export_yup=True,
        export_image_format="WEBP",
        export_image_quality=60,
    )
    print("GLB_SAVED", out_glb, f"{os.path.getsize(out_glb)/1e6:.1f}MB")

    spec = app_spec()
    spec["triangles"] = total
    out_spec = os.path.join(REPO, "scripts", "wrenfield-spec.json")
    with open(out_spec, "w") as f:
        json.dump(spec, f, indent=1)
    print("SPEC_SAVED", out_spec, {k: len(v) for k, v in spec.items() if isinstance(v, list)})


# Guarded: export_furniture.py imports the texture helpers above, and an
# unguarded call rebuilt and re-exported the whole house on every import.
if __name__ == "__main__":
    main()
