"""Export Wrenfield House for the walkthrough app.

Rebuilds the house from scratch (fast: assets are cached), then:
  - deletes every door leaf, leaving the cased openings in the walls;
  - strips the cosmetic bevel modifiers, whose 2 mm rounds multiply the
    triangle count for no visible gain at walkthrough scale;
  - decimates the heaviest imported assets until the whole model fits the
    app's 500k-triangle collision budget;
  - exports public/models/wrenfield_house.glb;
  - writes scripts/wrenfield-meta.json with doors, stairs and rooms already
    converted to app coordinates.

Coordinate note: Blender is Z-up, glTF is Y-up, so a plan point (x, y)
lands at (x, -y) on the app's XZ ground plane. Elevations carry over.

    blender --background --python export_app.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import bpy

from lib import architecture as arch
from lib import furnish, geometry as g, materials as m, plan as P, shell

BUDGET = 470_000  # headroom under the app's 500k octree budget


def clean():
    for coll in (bpy.data.objects, bpy.data.meshes, bpy.data.materials,
                 bpy.data.lights, bpy.data.cameras, bpy.data.collections):
        for item in list(coll):
            coll.remove(item, do_unlink=True)


def bake_tiling_textures():
    """Replace each node-driven Base Color with a real tiling image.

    glTF carries a constant colour or an image and nothing else, so the
    patterns are regenerated by lib/bake.py and plugged in as image textures.
    The geometry then gets world-space box UVs scaled to each material's tile
    size, which is what makes one 512px image cover a whole floor without
    unwrapping a single object.
    """
    import json as _json
    from lib import bake

    baked = 0
    for mat in bpy.data.materials:
        gen = mat.get("bake_gen")
        if not gen or not mat.use_nodes:
            continue
        bsdf = next((n for n in mat.node_tree.nodes if n.type == "BSDF_PRINCIPLED"), None)
        if not bsdf:
            continue

        rgb = bake.generate(gen, _json.loads(mat["bake_params"]), mat.name)
        if rgb is None:
            continue

        # Match the pattern's average to the flat colour that was already
        # tuned and measured in-app. Baking adds grout lines and board joints,
        # which drag the mean down and would otherwise darken every floor by
        # about a quarter; scaling per channel keeps the hue and restores the
        # tone, so the texture adds detail without re-opening the palette.
        flat = mat.get("flat_color")
        if flat is not None:
            import numpy as _np
            current = rgb.reshape(-1, 3).mean(axis=0)
            rgb = _np.clip(rgb * (_np.asarray(flat) / _np.maximum(current, 1e-4)), 0.0, 1.0)
        img = bake.to_blender_image(f"tex_{mat.name}", rgb)

        nt = mat.node_tree
        tex = nt.nodes.new("ShaderNodeTexImage")
        tex.image = img
        tex.interpolation = "Smart"
        tex.extension = "REPEAT"
        tex.location = (-400, 200)
        # The UVs are already built at the right scale, so the node reads them
        # straight through with no mapping in between.
        uv = nt.nodes.new("ShaderNodeUVMap")
        uv.uv_map = UV_NAME
        uv.location = (-620, 200)
        nt.links.new(uv.outputs["UV"], tex.inputs["Vector"])

        base = bsdf.inputs["Base Color"]
        for link in list(base.links):
            nt.links.remove(link)
        nt.links.new(tex.outputs["Color"], base)
        baked += 1

    print(f"TEXTURES_BAKED {baked}")
    build_box_uvs()


UV_NAME = "UVMap"


def build_box_uvs():
    """Box-project every mesh, per face, at its own material's tile size.

    A face is projected onto whichever world plane it most faces, so a floor
    takes its UVs from X/Y and a wall from X/Z or Y/Z. Scaling by the material
    means a 2.4 m plank tile and a 1.2 m carpet tile both come out at real
    size on the same object.
    """
    import bmesh

    done = 0
    for obj in bpy.data.objects:
        if obj.type != "MESH" or not obj.data.polygons:
            continue

        tiles = []
        for slot in obj.data.materials:
            tiles.append(float(slot["bake_tile"]) if slot and slot.get("bake_tile") else 0.0)
        if not any(tiles):
            continue

        mw = obj.matrix_world
        bm = bmesh.new()
        bm.from_mesh(obj.data)
        layer = bm.loops.layers.uv.get(UV_NAME) or bm.loops.layers.uv.new(UV_NAME)

        for face in bm.faces:
            tile = tiles[face.material_index] if face.material_index < len(tiles) else 0.0
            if tile <= 0:
                tile = 2.4
            n = (mw.to_3x3() @ face.normal)
            ax, ay, az = abs(n.x), abs(n.y), abs(n.z)
            for loop in face.loops:
                co = mw @ loop.vert.co
                if az >= ax and az >= ay:
                    u, v = co.x, co.y          # floors and ceilings
                elif ax >= ay:
                    u, v = co.y, co.z          # walls facing along X
                else:
                    u, v = co.x, co.z          # walls facing along Y
                loop[layer].uv = (u / tile, v / tile)

        bm.to_mesh(obj.data)
        bm.free()
        done += 1

    print(f"UV_PROJECTED {done}")


def flatten_procedural_materials():
    """Give every node-driven material a constant Base Color for export.

    The glTF exporter can write a baseColorFactor or a baseColorTexture and
    nothing else. A Base Color fed by a Noise/Brick/ColorRamp graph matches
    neither, so it silently exports as white — which is how a fully painted
    house arrived in the app as a colourless one. Each material recorded the
    colour its graph averages to when it was built; swap that in.
    """
    flattened = 0
    for mat in bpy.data.materials:
        if not mat.use_nodes:
            continue
        bsdf = next((n for n in mat.node_tree.nodes
                     if n.type == "BSDF_PRINCIPLED"), None)
        if not bsdf:
            continue
        base = bsdf.inputs["Base Color"]
        if not base.is_linked:
            continue
        flat = mat.get("flat_color")
        if flat is None:
            continue
        for link in list(base.links):
            mat.node_tree.links.remove(link)
        base.default_value = (flat[0], flat[1], flat[2], 1.0)
        flattened += 1
    print(f"MATERIALS_FLATTENED {flattened}")


def delete_doors():
    holders = [o for o in bpy.data.objects if o.get("is_door")]
    doomed = []
    for h in holders:
        doomed += [c for c in h.children_recursive] + [h]
    for o in doomed:
        bpy.data.objects.remove(o, do_unlink=True)
    print(f"DOORS_REMOVED {len(holders)}")


def strip_bevels():
    n = 0
    for o in bpy.data.objects:
        for mod in list(o.modifiers):
            if mod.type == "BEVEL":
                o.modifiers.remove(mod)
                n += 1
    print(f"BEVELS_STRIPPED {n}")


def visible_meshes():
    return [o for o in bpy.data.objects
            if o.type == "MESH" and not o.hide_render and not o.hide_viewport]


def evaluated_tris():
    """Triangle counts as the exporter will see them, modifiers applied."""
    dg = bpy.context.evaluated_depsgraph_get()
    per_mesh = {}   # mesh datablock -> (tris, [objects])
    for o in visible_meshes():
        me = bpy.data.meshes.new_from_object(o.evaluated_get(dg))
        tris = sum(len(p.vertices) - 2 for p in me.polygons)
        bpy.data.meshes.remove(me)
        key = o.data
        t, objs = per_mesh.get(key, (0, []))
        per_mesh[key] = (tris, objs + [o])
    return per_mesh


# Names of things that are imported assets rather than scripted architecture.
# Decimation is safe on these; collapse-decimating a box-built wall or worktop
# produces slivers, so the architecture is never touched.
ASSET_HINT = ("asset_", "sofa", "Sofa", "dchair", "barstool", "potted",
              "loft_sofa", "snug_chair", "bed1_lamp", "hanging_picture",
              "book_", "ceramic", "wooden_bo", "ornate", "Classic", "Ottoman",
              "ArmChair", "modern_", "mid_century", "side_table", "Television",
              "television", "desk_lamp", "classic_laptop", "dining_",
              "coffee_table", "liv_art")


def _is_asset(obj):
    return obj.name.startswith(ASSET_HINT)


def decimate_to_budget():
    """Cap every imported asset's mesh so the whole model fits the budget.

    Uses the modifier-apply OPERATOR rather than a hand-rolled depsgraph
    bake: the first version of this read evaluated geometry before the
    depsgraph had caught up, reported success, and exported the original
    dense meshes anyway. The operator path keeps Blender's own update
    ordering, and the result is verified from the mesh data itself.
    """
    for _pass in range(3):
        bpy.context.view_layer.update()
        per_mesh = evaluated_tris()
        total = sum(t * len(o) for t, o in per_mesh.values())
        print(f"TRIS_PASS{_pass} {total}")
        if total <= BUDGET:
            break

        for mesh, (tris, objs) in sorted(per_mesh.items(),
                                         key=lambda kv: -kv[1][0] * len(kv[1][1])):
            if not _is_asset(objs[0]):
                continue
            cap = min(10_000, max(2_500, 30_000 // len(objs)))
            if tris <= cap:
                continue

            host = objs[0]
            # modifier_apply refuses multi-user data, so split it first; every
            # copy is pointed at the decimated result afterwards.
            host.data = host.data.copy()
            mod = host.modifiers.new("shrink", "DECIMATE")
            mod.ratio = cap / tris
            with bpy.context.temp_override(object=host, active_object=host,
                                           selected_editable_objects=[host]):
                bpy.ops.object.modifier_apply(modifier=mod.name)

            done = sum(len(p.vertices) - 2 for p in host.data.polygons)
            for o in objs:
                o.data = host.data
            print(f"DECIMATED {host.name} {tris}->{done} x{len(objs)}")

    bpy.context.view_layer.update()
    total = sum(t * len(o) for t, o in evaluated_tris().values())
    print(f"TRIS_AFTER {total}")
    return total


LEAF_TRIMS = {"door_leaf": "trim_white", "cab_navy": "trim_charcoal",
              "cab_sage": "trim_white", "cab_oak": "trim_oak"}
HANDLE_TRIMS = {"brass": "metal_brass", "chrome": "metal_chrome",
                "black_metal": "metal_black", "steel": "metal_chrome"}

FLOOR_MAP = {"oak": "oak_parquet", "walnut": "walnut_boards",
             "tile_stone": "slate_tile", "tile_white": "ceramic_tile_white",
             "tile_slate": "slate_tile", "carpet_grey": "carpet_grey",
             "carpet_beige": "carpet_beige", "concrete": "polished_concrete"}


def app_rooms():
    """Room metadata in app coordinates — the app only uses it for the room
    readout, the jump list and its per-room lights; geometry comes from the
    GLB."""
    out = []
    storeys = [
        (P.GROUND_ROOMS, P.G, P.H_G, {"landing": None}),
        (P.FIRST_ROOMS, P.F1, P.H_F1, None),
        (P.ATTIC_ROOMS, P.F2, P.H_F2, None),
    ]
    voids = {("first", "landing"): [P.VOID_A, P.VOID_B],
             ("attic", "loft"): [P.VOID_B]}
    names = {"wc": "Cloakroom", "bed1": "Principal Bedroom", "loftbath": "Loft Shower Room"}

    for label, (rooms, elev, height) in zip(
            ("ground", "first", "attic"),
            [(r, e, h) for r, e, h, _ in storeys]):
        for rid, (poly, floor, _wall) in rooms.items():
            entry = {
                "id": f"{label}-{rid}",
                "name": names.get(rid, rid.replace("_", " ").title()),
                "polygon": [[x, -y] for x, y in poly],
                "voids": [[[x, -y] for x, y in v] for v in voids.get((label, rid), [])],
                "floor_finish": FLOOR_MAP.get(floor, "oak_parquet"),
                "ceiling_finish": "none",
                "height": height,
                "elevation": elev,
            }
            out.append(entry)
    return out


def main():
    clean()
    mats = m.library()
    cols, _ = shell.build(mats)
    furnish.build(cols, mats)

    # The exporter's use_visible does not reliably exclude the hidden import
    # masters, and an invisible master in Blender is a very visible pile of
    # furniture at the origin in the GLB. The placed copies own the mesh data
    # too, so the masters can simply go.
    masters = bpy.data.collections.get("_assets")
    if masters:
        for o in list(masters.objects):
            bpy.data.objects.remove(o, do_unlink=True)
        print("MASTERS_REMOVED")

    # Name the flights so the app can keep them out of its collision octree.
    # Their treads are drawn by the model but walked on via the ramp colliders
    # the scene spec adds; leaving the risers in the octree catches the
    # player's capsule a metre up. Balustrades keep colliding, deliberately.
    flights = sorted((o for o in bpy.data.objects if o.name.startswith("flight")),
                     key=lambda o: o.location.z)
    for i, o in enumerate(flights):
        # Rename the mesh data as well: three.js names a GLTF mesh object from
        # the glTF *mesh*, not the node, so renaming only the object leaves the
        # app matching against "flight" and excluding nothing.
        o.name = o.data.name = f"stairtreads_{i}"
    print("FLIGHTS_TAGGED", [o.name for o in flights])

    bake_tiling_textures()
    delete_doors()
    strip_bevels()
    total = decimate_to_budget()

    out_glb = os.path.join(REPO, "public", "models", "wrenfield_house.glb")
    bpy.ops.export_scene.gltf(
        filepath=out_glb,
        export_format="GLB",
        use_visible=True,
        export_apply=True,
        export_cameras=False,
        export_extras=False,
        export_yup=True,
        export_image_format="WEBP",
        export_image_quality=60,
    )
    print("GLB_SAVED", out_glb, f"{os.path.getsize(out_glb)/1e6:.1f}MB")

    doors = []
    for i, d in enumerate(arch.DOOR_REGISTRY):
        doors.append({
            "id": f"wd-{i}",
            "position": [round(d["x"], 3), round(-d["y"], 3)],
            "elevation": round(d["base"], 3),
            "yaw": round(d["yaw"], 2),
            "width": round(d["width"], 3),
            "height": round(d["height"], 3),
            "thickness": round(d["thickness"], 3),
            "door": {
                "type": "hinged",
                "swing": "inward_left" if d["swing"] < 0 else "inward_right",
                "leaf": LEAF_TRIMS.get(d["leaf"], "trim_white"),
                "frame": "trim_white",
                "handle": HANDLE_TRIMS.get(d["handle"], "metal_brass"),
                "lining": "none",   # the GLB already carries the casings
            },
        })

    sa, sb = P.STAIR_A, P.STAIR_B
    stairs = [
        {"id": "flight-a", "start": [(sa["x0"] + sa["x1"]) / 2, -sa["y0"]],
         "direction": "south", "width": sa["x1"] - sa["x0"],
         "base_height": sa["base"], "top_height": sa["top"],
         "run": sa["y1"] - sa["y0"], "steps": sa["steps"], "finish": "oak_parquet"},
        {"id": "flight-b", "start": [(sb["x0"] + sb["x1"]) / 2, -sb["y0"]],
         "direction": "south", "width": sb["x1"] - sb["x0"],
         "base_height": sb["base"], "top_height": sb["top"],
         "run": sb["y1"] - sb["y0"], "steps": sb["steps"], "finish": "oak_parquet"},
    ]

    meta = {"triangles": total, "doors": doors, "stairs": stairs, "rooms": app_rooms()}
    out_meta = os.path.join(REPO, "scripts", "wrenfield-meta.json")
    with open(out_meta, "w") as f:
        json.dump(meta, f, indent=1)
    print("META_SAVED", out_meta, f"doors={len(doors)} rooms={len(meta['rooms'])}")


main()
