"""Blender's Filmic view transform, as the public view draws it.

Filmic, as Blender's colour management ships it, takes scene-linear light
through a log2 shaper spanning 25 stops round middle grey, a 3D LUT that
eases very bright colours towards white, and a 1D contrast curve to display
values. Over any light a house holds the 3D LUT changes nothing by as much
as a display code — it only acts above eight times white — so the view
transform is, to within that, one curve applied to each channel: display
value against log2 of the light.

This samples that curve through Blender's own OpenColorIO config, every
quarter stop from its foot (2^-12.47) to where it reaches 1 (2^4.03, 16.3
times white), and writes it where the public view reads it
(frontend/Experience/Utils/filmicCurve.js). Drawn by linear interpolation
between the samples, it is within 0.06 of a display code of Blender's.

    blender --background --factory-startup --python blender/filmic_curve.py
    blender ... --python blender/filmic_curve.py -- --look "Medium High Contrast"
"""
import argparse
import os
import sys

import bpy
import numpy as np
import PyOpenColorIO as OCIO

# The Filmic Log shaper's range, in stops of scene-linear light: its foot,
# and the top of its latitude, where the curve has reached white.
LOG_MIN = -12.473931188
LOG_TOP = 4.026068812
STEP = 0.25

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "frontend", "Experience", "Utils",
                   "filmicCurve.js")


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    parser = argparse.ArgumentParser()
    parser.add_argument("--look", default="None")
    args = parser.parse_args(argv)

    path = os.path.join(bpy.utils.resource_path("LOCAL"), "datafiles", "colormanagement", "config.ocio")
    config = OCIO.Config.CreateFromFile(path)
    transform = OCIO.DisplayViewTransform(src="Linear Rec.709", display="sRGB", view="Filmic")
    if args.look != "None":
        transform = OCIO.GroupTransform([
            OCIO.LookTransform(src="Linear Rec.709", dst="Linear Rec.709", looks=args.look),
            transform,
        ])
    processor = config.getProcessor(transform).getDefaultCPUProcessor()

    stops = np.arange(LOG_MIN, LOG_TOP + STEP / 2, STEP)
    rgb = np.repeat((2.0 ** stops)[:, None], 3, axis=1).astype(np.float32).ravel().copy()
    processor.applyRGB(rgb)
    curve = np.clip(rgb.reshape(-1, 3)[:, 0], 0.0, 1.0)

    version = ".".join(str(v) for v in bpy.app.version[:2])
    values = ",\n".join("    " + ", ".join(f"{v:.6f}" for v in curve[i:i + 8]) for i in range(0, len(curve), 8))
    with open(OUT, "w") as f:
        f.write(
            f"// Generated by blender/filmic_curve.py from Blender {version}'s colour management — do not edit.\n"
            f"// Blender's Filmic view, look \"{args.look}\": the display value (sRGB-encoded) for scene-linear\n"
            f"// light at 2^(logMin + i * step), i = 0..{len(curve) - 1}.\n"
            f"export const FILMIC = {{\n"
            f"    look: \"{args.look}\",\n"
            f"    logMin: {LOG_MIN},\n"
            f"    step: {STEP},\n"
            f"    curve: [\n{values},\n    ],\n"
            f"}};\n"
        )
    print("FILMIC_CURVE", len(curve), "samples, look", args.look, "->", os.path.normpath(OUT))
    print("FILMIC_CHECK middle grey 0.18 ->", round(float(np.interp(np.log2(0.18), stops, curve)), 4),
          "white 1.0 ->", round(float(np.interp(0.0, stops, curve)), 4))


main()
