import * as THREE from "three";

import Sizes from "./Utils/Sizes.js";
import Time from "./Utils/Time.js";
import Resources from "./Utils/Resources.js";
import { lightmapURL } from "./Utils/device.js";
import assets from "./Utils/assets.js";

import Camera from "./Camera.js";
import Renderer from "./Renderer.js";
import Preloader from "./Preloader.js";

import World from "./World/World.js";

export default class Experience {
    static instance;

    /**
     * @param {HTMLCanvasElement} canvas
     * @param {import("socket.io-client").Socket} socket  Presence namespace.
     * @param {object} sceneSpec  Validated scene spec to build the world from.
     * @param {object} [options]
     * @param {boolean} [options.publicView]  a shared link: walk round and
     *        talk, nothing that edits or saves — and drawn as cheaply as it can be
     * @param {object} [options.published]  the published version it opens:
     *        `view` is the URL of its snapshot
     */
    constructor(canvas, socket, sceneSpec, { publicView = false, published = null } = {}) {
        if (Experience.instance) {
            return Experience.instance;
        }
        Experience.instance = this;

        this.canvas = canvas;
        this.socket = socket;
        this.sceneSpec = sceneSpec;
        this.publicView = publicView;
        this.published = published;

        this.sizes = new Sizes();
        this.time = new Time();

        this.setScene();
        this.setCamera();
        this.setRenderer();
        this.setResources();
        this.setPreloader();
        this.setWorld();

        this.sizes.on("resize", () => this.onResize());

        this.update();
    }

    setScene() {
        this.scene = new THREE.Scene();
    }

    setCamera() {
        this.camera = new Camera();
    }

    setRenderer() {
        this.renderer = new Renderer();
    }

    setResources() {
        // An imported scene's GLB is queued alongside the avatars so the
        // preloader's progress bar covers the whole download, not just the
        // characters. Procedural scenes add nothing here.
        // Model URLs are stored relative (`/models/x.glb`) so a spec never
        // carries a hostname. VITE_MODEL_BASE points them at a CDN in
        // deployments, where the GLBs are uploaded rather than committed.
        const base = (import.meta.env?.VITE_MODEL_BASE || "").replace(/\/+$/, "");
        // The kit of parts generated buildings are dressed with — door
        // leaves, casings, window frames, balusters — from
        // blender/export_kit.py. Without it they are drawn in plain boxes.
        const extra = [{ name: "kit", type: "glbModel", path: base + "/models/kit.glb" }];
        // The car is only loaded by scenes that place one. Both parts are
        // generated by blender/export_car.py.
        if (this.sceneSpec.vehicles?.length) {
            extra.push(
                { name: "carChassis", type: "glbModel", path: base + "/models/car-chassis.glb" },
                { name: "carWheel", type: "glbModel", path: base + "/models/car-wheel.glb" }
            );
        }

        // A published version with a runtime file builds none of the house,
        // so an imported model — drawn by the snapshot — is not needed.
        const runtime = this.published?.runtime;
        const sceneAssets = this.sceneSpec.model && !runtime
            ? [
                  {
                      name: "sceneModel",
                      type: "glbModel",
                      path: base + this.sceneSpec.model.url,
                  },
              ]
            : [];

        // A published public view draws its static scene from the snapshot,
        // lit — once baked — by its day lightmap to start with.
        if (this.published?.view) extra.push({ name: "publishedView", type: "glbModel", path: this.published.view });
        if (runtime) extra.push({ name: "publishedRuntime", type: "glbModel", path: runtime });
        const day = this.published?.lighting?.variants?.day;
        if (day) extra.push({ name: "lightmap:day", type: "imageTexture", path: lightmapURL(day) });

        this.resources = new Resources([...assets, ...sceneAssets, ...extra]);
    }

    setPreloader() {
        this.preloader = new Preloader();
    }

    setWorld() {
        this.world = new World();
    }

    onResize() {
        this.camera.onResize();
        this.renderer.onResize();
    }

    update() {
        if (this.preloader) this.preloader.update();

        // World before camera: under pointer lock the camera places itself
        // from the player's position, so moving the player first keeps the
        // two in lockstep instead of a frame apart.
        if (this.world) this.world.update();
        if (this.camera) this.camera.update();
        // Publishing borrows the renderer for a while (Publish/Snapshot.js).
        if (this.renderer && !this.suspended) this.renderer.update();
        if (this.time) this.time.update();

        window.requestAnimationFrame(() => this.update());
    }
}
